version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    working_dir: /app
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_CONFIG_FILE: ./rabbitmq.conf
    ports:
      - "5673:5673"
      - "15672:15672"
    volumes:
      - .:/app
    working_dir: /app
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "profeta@indt.org.br"
      PGADMIN_DEFAULT_PASSWORD: "PR0FETA!"
    ports:
      - "15432:80"
    depends_on:
      - postgres


